return {
  { "webhooked/kanso.nvim" },
  { "sainnhe/gruvbox-material" },
  { "xero/miasma.nvim" },
  { "folke/tokyonight.nvim" },
  { "catppuccin/nvim" },
  { "ptdewey/darkearth-nvim" },
  { "savq/melange-nvim" },
  { "mellow-theme/mellow.nvim" },
  { "ramojus/mellifluous.nvim" },
  { "sainnhe/everforest" },
  { "rakr/vim-two-firewatch" },
  { "gmr458/cold.nvim" },
  { "vv9k/bogster" },
  { "ayu-theme/ayu-vim" },
  { "lucasadelino/conifer.nvim" },
  { "Mofiqul/vscode.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "jaredgorski/fogbell.vim" },
  { "datsfilipe/vesper.nvim" },
  { "YorickPeterse/Autumn.vim" },
  { "blazkowolf/gruber-darker.nvim" },
  { "junegunn/seoul256.vim" },
  { "shaunsingh/nord.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "vague-theme/vague.nvim" },
  { "everviolet/nvim", name = "evergarden" },
  { "casedami/neomodern.nvim" },
  { "olivercederborg/poimandres.nvim" },
  -- { "metalelf0/black-metal-theme-neovim" },
  {
    "WTFox/jellybeans.nvim",
    opts = { bold = false },
  },
  {
    "zenbones-theme/zenbones.nvim",
    dependencies = "rktjmp/lush.nvim",
    priority = 1000,
  },
  {
    "ellisonleao/gruvbox.nvim",
    priority = 1000,
    config = true,
    opts = {
      bold = false,
      contrast = "hard",
      italic = {
        strings = true,
        emphasis = false,
        comments = true,
        operators = false,
        folds = true,
      },
    },
  },
}
