### GENERAL ###

set -g default-shell /usr/bin/zsh
# set -g prefix C-Space
set -g prefix C-e
unbind C-b
# bind C-Space send-prefix
bind C-e send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g detach-on-destroy off
set -g mouse on
set -g history-limit 50000
set -g focus-events on
set -s escape-time 0
set -g mode-keys vi

bind r source-file ~/.config/tmux/tmux.conf \; display -d 1000 "config reloaded"

# performance optimizations for neovim
set -sg escape-time 0
set -g focus-events on
set -g history-limit 50000

# enable mouse support
set -g mouse on

### PANES & WINDOWS ###

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 3
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3

bind -r n next-window
bind -r p previous-window
bind w choose-tree -Zw
bind S choose-tree -Zs

### COPY MODE (hu layout lol) ###

bind ő swap-pane -U
bind ú swap-pane -D
bind Ő copy-mode
bind Ú paste-buffer
bind '[' copy-mode
bind ']' paste-buffer

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-no-clear 'wl-copy'

### VISUAL AESTHETICS ###

### COLOR ###

set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

set -g status on
set -g status-position bottom
set -g status-interval 5

set -g status-style bg=colour235,fg=colour250

set -g pane-border-indicators both
set -g pane-border-style fg=colour240
set -g pane-active-border-style fg=colour240
# set -g pane-active-border-style fg=colour250

set -g message-style bg=colour235,fg=colour255
set -g message-command-style bg=colour235,fg=colour255

set -g mode-style bg=colour250,fg=colour235

### STATUSLINE ###

set -g status-left-length 100
set -g status-right-length 100

set -g status-left "#[fg=colour235,bg=colour246,bold] #S #[fg=colour246,bg=colour235,nobold] "
set -g window-status-format "#[fg=colour250,bg=colour235] #I: #W "
set -g window-status-current-format "#[fg=colour235,bg=colour238]#[fg=colour255,bg=colour238] #I: #W #[fg=colour238,bg=colour235]"
set -g status-right "#[fg=colour238,bg=colour235]#[fg=colour255,bg=colour238] %d %b  %H:%M #[fg=colour246,bg=colour238]#[fg=colour235,bg=colour246,bold] #h "
