### KEYBINDINGS ###
bindkey "^a" beginning-of-line
bindkey "^e" end-of-line
bindkey "^u" kill-line
bindkey "^b" backward-word
bindkey "^[[1;5D" backward-word
bindkey "^l" forward-word
bindkey "^[[1;5C" forward-word
bindkey "^J" history-search-forward
bindkey "^K" history-search-backward
